const Mongoose=require('mongoose');
const goodScheame=Mongoose.Schema;
let schema = new goodScheame({
    _id:{
        type:Object
    },
    s_collect:{
        type:Number
    },
    s_img_more:{
        type:Array
    },
    s_sendDescribe:{
        type:Array
    },
    s_shop_recommend:{
        type:Array
    },
    s_shop_vendre:{
        type:Number
    },
    s_uid:{
        type:Number
    },
    s_vip:{
        type:Number
    },
    s_type:{
        type:String
    },
    s_msg:{
        type:String
    },
    s_newPrice:{
        type:Number
    },
    s_oldPrice:{
        type:Number
    },
    s_img_one:{
        type:String
    },
    s_transport:{
        type:String
    },
    s_adress:{
        type:String
    },
    s_shop_type:{
        type:String
    },
    s_shop_mes:{
        type:String
    }
    
  })
  module.exports=Mongoose.model('goodsModel',schema);